import Payment from "@/components/payment/payment";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { Inter } from "next/font/google";
import Header from "@/components/Header or Navbar/Header";
import { Providers } from "@/redux/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
